### ISSUE TITLE
Support for var inside transition

### ISSUE THREAD

**Issue by OfficialCRUGG** [octfx/mediawiki-extensions-TemplateStylesExtender#15]
Using this extension, I am able to use
```css
transition: all; 
transition-duration: var(--transition-duration);
```
but not
```css
transition: all var(--transition-duration);
```

**Comment by octfx** [comment]
Are you using the master or develop branch?

Your second example works for me using the current develop commit b6a62fbfb52184c6f89b27750c1ed099995ed7eb
