### ISSUE TITLE
Installation instructions missing

### ISSUE THREAD

**Issue by Hasenhirn** [octfx/mediawiki-extensions-TemplateStylesExtender#2]
Hi there,

I would love to use your extension, unfortunately the zip file (as stated by the extension page on mediawiki.org) is missing and I do not know how to install it via repository.

Could you maybe provide the zip file again or describe how to install via git?
Thank you very much!

**Comment by octfx** [comment]
I've fixed the link, you can download the extension at https://github.com/octfx/mediawiki-extensions-TemplateStylesExtender/archive/refs/heads/master.zip

**Comment by Hasenhirn** [comment]
Lovely, thank you!
