### ISSUE TITLE
Add support for clamp()

### ISSUE THREAD

**Issue by Keyacom** [octfx/mediawiki-extensions-TemplateStylesExtender#5]
MDN: https://developer.mozilla.org/en-US/docs/Web/CSS/clamp
Caniuse: https://caniuse.com/mdn-css_types_clamp

`clamp(<value1>,<value2>,<value3>)` is technically the same thing as `max(<value1>,min(<value2>,<value3>))`, but it's nice to have. Values:
- `<value1>` - minimum value
- `<value2>` - preferred value
- `<value3>` - maximum value

**Comment by octfx** [comment]
Implementing `clamp` for all allowed positions is currently not really feasible.  
The current implementation should work for `(min/max-)height/width`
