### ISSUE TITLE
Add support for revert and revert-layer

### ISSUE THREAD

**Issue by Keyacom** [octfx/mediawiki-extensions-TemplateStylesExtender#6]
`revert` and `revert-layer` are now CSS-wide keywords.

`revert`:
MDN: https://developer.mozilla.org/en-US/docs/Web/CSS/revert
Caniuse: https://caniuse.com/mdn-css_types_global_keywords_revert

`revert-layer`:
MDN: https://developer.mozilla.org/en-US/docs/Web/CSS/revert-layer
Caniuse: https://caniuse.com/mdn-css_types_global_keywords_revert-layer

**Comment by octfx** [comment]
Done in v1.1.0
